(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(setq use-package-always-ensure t)
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile (require 'use-package))

(add-to-list 'load-path "~/.emacs.d/lisp/")
(require 'init-general)
(require 'init-evil)
(require 'init-functions)
(require 'init-electric)
(require 'init-auto-complete)
(require 'init-ivy)
(require 'init-org-bullets)
(require 'init-jbeans-theme)
(require 'init-js2-mode)
(require 'init-flycheck)
(require 'init-tern)
(require 'init-ac-html)
; (require 'init-web-mode)
(require 'init-polymode)
